### ISSUE TITLE
v9.9.0 dark extended chunks not fixed

### ISSUE THREAD

**Issue by lordbaygon** [EuSouVoce/FartherViewDistance_1.20.1#4]
everything else's working fine, except the extended chunks still being darkened

paper version: 1.21-27
plugin version: 9.9.0

**Comment by Taiyou06** [comment]
can replicate it 
![image](https://github.com/EuSouVoce/FartherViewDistance_1.20.1/assets/77050201/7a1814bf-aeb9-4ca5-a801-08bf69b96956)

Current Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6)
Plugin version: 9.9.0

**Comment by EuSouVoce** [comment]
Fixed in v9.9.2
